Fix bug in notification import
When removing a string from a list of strings, `del list["string"]` will cause a "TypeError: list indices must be integers or slices, not str".

File "/usr/local/lib/python3.7/site-packages/tower_cli/cli/transfer/send.py", line 1503, in import_notification_relations
  del existing_notifications[notification_name]
TypeError: list indices must be integers or slices, not str